name: Cypress E2E

on:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest  #  виртуальная машина GitHub
    steps:
      - uses: actions/checkout@v4

      - name: Run Cypress tests
        working-directory: cypress
        env:
          BASE_URL: https://food-63.ru  
        run: |
          npm install
          npx cypress run --headless
